### ISSUE TITLE
Events not firing on RN 0.39

### ISSUE THREAD

**Issue by iDams** [inProgress-team/react-native-youtube#110] opened 2017-02-07 22:11 UTC
Hey,

I'm using react-native `0.39` and no events are firing on IOS (`onReady`, `onChangeState`,...)
I didn't see any issues on it, am I the only one?

I fixed it by using `sendAppEventWithName` instead of `sendInputEventWithName ` to dispatch events from React Native to JS. Btw it seems that `sendInputEventWithName` is deprecated.

It might be the same issue as #108?

If anyone is having the same issue, I will do a PR ;)

**Comment by jonwu** [comment] 2017-02-08 16:31
same issue +1

**Comment by max-mykhailenko** [comment] 2017-02-08 16:45
It's duplicate of #108

**Comment by jonwu** [comment] 2017-02-08 17:28
@iDams i replaced `sendInputEventWithName` with `sendAppEventWithName` in Libraries > RCTYoutube.xcodeproj > RCTYoutube > RCTYoutube.m, but it still isn't working. Am i missing something?

**Comment by iDams** [comment] 2017-02-08 17:35
@jonwu You also need to change the way you listen to events in `YouTube.ios.js`. You have to use `NativeAppEventEmitter.addListener()` now

You can check the changes I made on my fork:
https://github.com/iDams/react-native-youtube/commit/3eb3344bd48379b67266dcfc759aeb034010d20f#diff-20f3ec9d61e7a9aa3d583adf9e66d4ffR62

Here is the doc related: https://facebook.github.io/react-native/docs/native-modules-ios.html#sending-events-to-javascript

**Comment by max-mykhailenko** [comment] 2017-02-09 06:43
@iDams can you create PR with this changes?

**Comment by wcandillon** [comment] 2017-02-10 06:53
@iDams I would love to see this commit merged, I will try to test it on an integration branch that also contains the build fix for react native 0.4.0 currently in master.

**Comment by wcandillon** [comment] 2017-02-10 08:38
@iDams @max-mykhailenko I made an integration branch that works great for my project! 🎉  I will try to make a clean PR for you now.

**Comment by iDams** [comment] 2017-02-10 08:48
@wcandillon nice! Sorry for the late responses, I didn't have time to do the PR yet.

**Comment by wcandillon** [comment] 2017-02-10 09:12
@iDams @max-mykhailenko  ready at https://github.com/inProgress-team/react-native-youtube/pull/113. I use it in my own react native project and it works great. Thank you for such great component and for your support guys.

**Closed** 2017-02-12 17:53 UTC
