### ISSUE TITLE
Video not loading unless rotate device

### ISSUE THREAD

**Issue by choungchamnab** [inProgress-team/react-native-youtube#156] opened 2017-05-16 08:06 UTC
I've loaded the video but it not display unless I rotate device. Please guide.

**Comment by KingjZhang** [comment] 2017-05-18 18:39
I got the same issue on Android with ReactNative 0.43.3.

**Comment by KingjZhang** [comment] 2017-05-18 19:14
I got this error  'Youtube onError', 'UNAUTHORIZED_OVERLAY'

05-18 15:14:12.311 22662 22732 I ReactNativeJS: 'Youtube onReady', { target: 533 }
05-18 15:14:12.426 22662 22732 I ReactNativeJS: 'Youtube onChangeState', 'stopped'
05-18 15:14:12.427 22662 22732 I ReactNativeJS: 'Youtube onChangeState', 'loading'
05-18 15:14:12.855 22662 22732 I ReactNativeJS: 'Youtube onChangeState', 'started'
05-18 15:14:12.939 22662 22732 I ReactNativeJS: 'Youtube onChangeState', 'buffering'
05-18 15:14:16.320 22662 22732 I ReactNativeJS: 'Youtube onChangeState', 'playing'
05-18 15:14:17.371 22662 22732 I ReactNativeJS: 'Youtube onError', 'UNAUTHORIZED_OVERLAY'
05-18 15:14:17.446 22662 22732 I ReactNativeJS: 'Youtube onChangeState', 'stopped'

**Comment by gerardcuadras** [comment] 2017-05-20 12:32
Same here: UNAUTHORIZED_OVERLAY
Only works if I set:
> play={true}
> fullscreen={true}
but I don't want the video to start in full screen.

I don't have anything else in the view. Only the Youtube component.

**Comment by bethqiang** [comment] 2017-06-06 20:50
Has anyone found a solution to this? The `fullscreen={true}` works for me, but it's not necessarily what I'd call preferable. 😅

**Comment by tafelito** [comment] 2017-06-09 05:05
same error here. Duplicate of #161

**Comment by davidohayon669** [comment] 2017-06-24 22:07
#161

**Closed by davidohayon669** 2017-06-24 22:07 UTC
