### ISSUE TITLE
Play rotated without changing "orientation"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [inProgress-team/react-native-youtube#87] opened 2016-12-02 02:08 UTC
I'm making an app that is locked to portrait, and then occasionally we want to play landscape videos without changing the orientation (or rather without using "gravity" to rotate, the way apps typically do).

We'd like to play a landscape video on a "portrait" screen-- is this possible? i.e. rotated 90 degrees on purpose.

**Comment by cihancil** [comment] 2016-12-06 08:27
I got the same issue. I considered using orientation library to manually let landscape. But it does not help because player does not have full screen events

**Comment by Liroo** [comment] 2016-12-06 09:24
Duplicate of #84

**Closed** 2016-12-06 19:26 UTC
