### ISSUE TITLE
Video is getting paused immediately after starting

### ISSUE THREAD

**Issue by ursNj** [inProgress-team/react-native-youtube#398] opened 2019-10-03 09:57 UTC
this is the code im using 

<YouTube
          videoId="umAgdVTBae0" // The YouTube video ID
          apiKey={APP_CONFIG.youtubeKey}
          play={true} // control playback of video with true/false
          showFullscreenButton
          fullscreen={this.state.fullscreen} // control whether the video should play in fullscreen or inline
          onChangeFullscreen={e => {
            this.setState({fullscreen: e.isFullscreen});
          }}
          // loop // control whether the video should loop when ended
          // onReady={e => this.setState({isReady: true})}
          // onChangeState={e => this.setState({ status: e.state })}
          // onChangeQuality={e => this.setState({ quality: e.quality })}
          onError={e => console.log('ERROR', e)}
          controls={2}
          style={{flex: 1, alignSelf: 'stretch'}}
        />

**Comment by Sumit-Chakole** [comment] 2019-10-04 12:54
I too have same issue

**Comment by srfaytkn** [comment] 2019-10-05 08:50
you can use https://github.com/up-inside/react-native-youtube-sdk

**Comment by valerusg** [comment] 2019-10-07 08:16
Is happening the same problem as here: [https://github.com/inProgress-team/react-native-youtube/issues/390](https://github.com/inProgress-team/react-native-youtube/issues/390)

**Comment by bhaveshsilversky** [comment] 2019-10-08 09:02
I was having the same issue the video will play for second and will pause. the issue that I was facing was related to the height of the youtube player I decrease the height of the player and it plays smoothly. I think the logic behind this could be like if the youtube video overflow the device then it may be causing a problem.

**Comment by davidohayon669** [comment] 2019-10-09 15:31
@ursNj, @Sumit-Chakole the [Android Lib](https://developers.google.com/youtube/android/player/) we're wrapping is problematic when it comes to covering it with other views, or reducing the size of the player. Wrapped inside React Native I guess introduce more problems with other RN navigation components that might block the Player view in unnoticable ways. @valerusg gave good issues to learn more from

**Comment by davidohayon669** [comment] 2019-10-09 15:35
Duplicate of #161

**Closed** 2019-10-09 15:35 UTC
Labels: duplicate

**Comment by architch** [comment] 2021-02-19 16:55
Video is paused when the player not fully displayed on the screen. In my case I was putting it inside the ScrollView and when scrolled it down a bit, the video is paused. 
To avoid this , I removed the player out of the ScrollView and fixed it on top a parent View,  post which the video did not pause while browsing through other elements on the screen.

**Comment by mjm918** [comment] 2022-05-17 14:24
i'm using `PagerView` and facing the same issue.
