### ISSUE TITLE
'WKYTPlayerView.h' file not found

### ISSUE THREAD

**Issue by MITDD6338** [inProgress-team/react-native-youtube#415] opened 2019-11-11 10:24 UTC
I've tried and retried this many times, same error. Currently the steps I've taken:

npm install react-native-youtube -S

Project in Xcode -> Libraries -> Add Files -> node_modules/react-native-youtube/RCTYouTube.xcodeproj

Then the main project -> Build Phases -> Link Binary With Libraries +libRCTYouTube
npm run ios

Then I am receive:
.../node_modules/react-native-youtube/RCTYouTube.h:1:9: fatal error: 'WKYTPlayerView.h' file not found #import "WKYTPlayerView.h" ^~~~~~~~~~~~~~~~~~

![image](https://user-images.githubusercontent.com/31823903/68579834-1828f200-049b-11ea-8a24-1ee69fa97d3c.png)

<img width="990" alt="Screenshot 2019-11-11 at 3 51 38 PM" src="https://user-images.githubusercontent.com/31823903/68579879-35f65700-049b-11ea-9837-f71412a4ff1a.png">

Any idea what this may be caused by? 
@MadRabbit @jaygarcia @jeanregisser @faceyspacey @edmundito 

**PLATFIORM**

"react-native": "0.59.10",
 "react": "16.8.3",
  "react-native-youtube": "^2.0.0",

**Comment by davidohayon669** [comment] 2019-11-15 19:38
duplicate of #389

**Closed** 2019-11-15 19:39 UTC
