### ISSUE TITLE
Andriod Issue:- Binary XML file line #9: Error inflating class fragment

### ISSUE THREAD

**Issue by chetnadaffodil** [inProgress-team/react-native-youtube#73] opened 2016-09-30 06:59 UTC
#64

![screenshot_2016-09-30-12-26-27](https://cloud.githubusercontent.com/assets/17562095/18983282/763a1c42-8709-11e6-9081-059c19c6fcd2.png)

**Comment by mikelambert** [comment] 2016-10-05 06:31
I believe this happens when attempting to hot-reload with a video player active. I believe it comes from a conflict of triggering a re-load of the youtube xml fragment, where it errors because the associated ids are already in memory: `Binary XML file line #9: Duplicate id 0x7f0e00a7, tag null, or parent id 0x7f0e00a6 with another fragment for com.google.android.youtube.player.YouTubePlayerFragment`

The longer stack trace is:
```
E/AndroidRuntime( 3789): Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class fragment
E/AndroidRuntime( 3789): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:763)
E/AndroidRuntime( 3789): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
E/AndroidRuntime( 3789): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
E/AndroidRuntime( 3789): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
E/AndroidRuntime( 3789): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
E/AndroidRuntime( 3789): 	at android.view.View.inflate(View.java:18532)
E/AndroidRuntime( 3789): 	at com.inprogress.reactnativeyoutube.YouTubeView.init(YouTubeView.java:34)
E/AndroidRuntime( 3789): 	at com.inprogress.reactnativeyoutube.YouTubeView.<init>(YouTubeView.java:26)
E/AndroidRuntime( 3789): 	at com.inprogress.reactnativeyoutube.YouTubeManager.createViewInstance(YouTubeManager.java:39)
E/AndroidRuntime( 3789): 	at com.inprogress.reactnativeyoutube.YouTubeManager.createViewInstance(YouTubeManager.java:15)
E/AndroidRuntime( 3789): 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
E/AndroidRuntime( 3789): 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
E/AndroidRuntime( 3789): 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
E/AndroidRuntime( 3789): 	at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776)
E/AndroidRuntime( 3789): 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
E/AndroidRuntime( 3789): 	at com.facebook.react.uimanager.UIViewOperationQueue.pauseFrameCallback(UIViewOperationQueue.java:823)
E/AndroidRuntime( 3789): 	at com.facebook.react.uimanager.UIImplementation.onHostPause(UIImplementation.java:621)
E/AndroidRuntime( 3789): 	at com.facebook.react.uimanager.UIManagerModule.onHostPause(UIManagerModule.java:115)
E/AndroidRuntime( 3789): 	at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:179)
E/AndroidRuntime( 3789): 	at com.facebook.react.XReactInstanceManagerImpl.moveToBeforeResumeLifecycleState(XReactInstanceManagerImpl.java:591)
E/AndroidRuntime( 3789): 	at com.facebook.react.XReactInstanceManagerImpl.onHostPause(XReactInstanceManagerImpl.java:490)
E/AndroidRuntime( 3789): 	at com.facebook.react.XReactInstanceManagerImpl.onHostPause(XReactInstanceManagerImpl.java:501)
E/AndroidRuntime( 3789): 	at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:113)
E/AndroidRuntime( 3789): 	at com.facebook.react.ReactActivity.onPause(ReactActivity.java:62)
E/AndroidRuntime( 3789): 	at android.app.Activity.performPause(Activity.java:6101)
E/AndroidRuntime( 3789): 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1310)
E/AndroidRuntime( 3789): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3246)
E/AndroidRuntime( 3789): 	... 11 more
E/AndroidRuntime( 3789): Caused by: java.lang.IllegalArgumentException: Binary XML file line #9: Duplicate id 0x7f0e00a7, tag null, or parent id 0x7f0e00a6 with another fragment for com.google.android.youtube.player.YouTubePlayerFragment
E/AndroidRuntime( 3789): 	at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2120)
E/AndroidRuntime( 3789): 	at android.app.Activity.onCreateView(Activity.java:5328)
E/AndroidRuntime( 3789): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
E/AndroidRuntime( 3789): 	... 37 more
```

**Comment by mikelambert** [comment] 2016-10-05 06:38
Oops sorry, this is a dupe of https://github.com/inProgress-team/react-native-youtube/issues/64 which has much better discussion going on. Can you close this?

**Closed** 2017-05-09 16:34 UTC
